require('dotenv').config();
const express = require('express');
const cors = require('cors');
const axios = require('axios');
const { Client, GatewayIntentBits } = require('discord.js');

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;
const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const KEYS_CHANNEL_ID = '1496851498104131614';

// --- DISCORD DATABASE SYSTEM ---
const discordClient = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent
    ]
});

// Memory cache for fast lookups
// Structure: { "DF-XXX...": { msgId: "123", expiry_date: "...", hwidset: true, hwid: "...", duration_days: 7 } }
const keysCache = new Map();
let isCacheReady = false;

function parseKeyMessage(content) {
    try {
        // Extract JSON from markdown block
        const match = content.match(/```json\n([\s\S]*?)\n```/);
        if (match && match[1]) {
            return JSON.parse(match[1]);
        }
    } catch (e) {
        return null;
    }
    return null;
}

async function loadKeys() {
    try {
        const channel = await discordClient.channels.fetch(KEYS_CHANNEL_ID);
        if (!channel) return console.error("Could not find keys channel!");

        console.log("Fetching key database...");
        let lastId = undefined;
        let messagesFetched = 0;
        
        while (true) {
            const options = { limit: 100 };
            if (lastId) options.before = lastId;
            
            const messages = await channel.messages.fetch(options);
            if (messages.size === 0) break;
            
            for (const [id, msg] of messages) {
                const data = parseKeyMessage(msg.content);
                if (data && data.key) {
                    keysCache.set(data.key, {
                        msgId: id,
                        expiry_date: data.expiry_date,
                        hwidset: data.hwidset || false,
                        hwid: data.hwid,
                        duration_days: data.duration_days
                    });
                }
                lastId = id;
            }
            messagesFetched += messages.size;
            if (messages.size < 100) break;
        }
        isCacheReady = true;
        console.log(`Loaded ${keysCache.size} keys into memory. Cache is ready!`);
    } catch (e) {
        console.error("Error loading keys:", e);
    }
}

discordClient.on('ready', () => {
    console.log(`Database Bot logged in as ${discordClient.user.tag}`);
    loadKeys();
});

// Listen for new keys generated by the bot
discordClient.on('messageCreate', (msg) => {
    if (msg.channelId === KEYS_CHANNEL_ID) {
        const data = parseKeyMessage(msg.content);
        if (data && data.key) {
            keysCache.set(data.key, {
                msgId: msg.id,
                expiry_date: data.expiry_date,
                hwidset: data.hwidset || false,
                hwid: data.hwid,
                duration_days: data.duration_days
            });
            console.log(`New key added to cache: ${data.key}`);
        }
    }
});

// Listen for deleted keys (bans/removals)
discordClient.on('messageDelete', (msg) => {
    if (msg.channelId === KEYS_CHANNEL_ID) {
        for (const [key, val] of keysCache.entries()) {
            if (val.msgId === msg.id) {
                keysCache.delete(key);
                console.log(`Key removed from cache: ${key}`);
                break;
            }
        }
    }
});

// Listen for manual edits (e.g. unbinding HWID manually)
discordClient.on('messageUpdate', (oldMsg, newMsg) => {
    if (newMsg.channelId === KEYS_CHANNEL_ID) {
        const data = parseKeyMessage(newMsg.content);
        if (data && data.key) {
            keysCache.set(data.key, {
                msgId: newMsg.id,
                expiry_date: data.expiry_date,
                hwidset: data.hwidset || false,
                hwid: data.hwid,
                duration_days: data.duration_days
            });
        }
    }
});

if (DISCORD_TOKEN) {
    discordClient.login(DISCORD_TOKEN);
} else {
    console.error("No DISCORD_TOKEN provided for server DB!");
}

// --- EXPRESS API ---

async function verifyLicense(licenseKey, hwid) {
    // Wait for cache to be ready if server just woke up from sleep
    let retries = 0;
    while (!isCacheReady && retries < 15) {
        await new Promise(r => setTimeout(r, 1000));
        retries++;
    }

    if (!isCacheReady) {
        return { valid: false, error: "Server is starting up. Please try again in 5 seconds." };
    }

    const keyData = keysCache.get(licenseKey);
    
    if (!keyData) {
        return { valid: false, error: "Invalid or non-existent key." };
    }

    const expiryTimestamp = new Date(keyData.expiry_date.replace(" UTC", "Z")).getTime();
    if (Date.now() > expiryTimestamp) {
        return { valid: false, error: "This key has expired." };
    }

    // HWID Binding System
    if (!keyData.hwidset || keyData.hwid === null) {
        // Bind the HWID
        keyData.hwidset = true;
        keyData.hwid = hwid;
        keysCache.set(licenseKey, keyData); // update cache

        // Update Discord Message to save HWID permanently
        try {
            const channel = await discordClient.channels.fetch(KEYS_CHANNEL_ID);
            const msgToEdit = await channel.messages.fetch(keyData.msgId);
            if (msgToEdit) {
                const newData = {
                    key: licenseKey,
                    duration_days: keyData.duration_days,
                    expiry_date: keyData.expiry_date,
                    hwidset: true,
                    hwid: hwid
                };
                await msgToEdit.edit(`\`\`\`json\n${JSON.stringify(newData, null, 2)}\n\`\`\``);
                console.log(`Bound HWID ${hwid} to key ${licenseKey}`);
            }
        } catch (e) {
            console.error(`Failed to update HWID in Discord for key ${licenseKey}:`, e);
        }
        return { valid: true };
    } else if (keyData.hwid !== hwid) {
        return { valid: false, error: "Key is already bound to another device. Please purchase a new key or contact support to reset HWID." };
    }

    return { valid: true };
}

app.post('/api/chat', async (req, res) => {
    const { key, hwid, payload, endpoint } = req.body;

    if (!key) {
        return res.status(400).json({ error: 'License key is required.' });
    }

    if (!DISCORD_TOKEN) {
        return res.status(500).json({ error: 'Server database is currently offline.' });
    }

    // 1. Verify Key
    const keyCheck = await verifyLicense(key, hwid);
    if (!keyCheck.valid) {
        return res.status(401).json({ error: keyCheck.error });
    }

    // 2. Forward request
    try {
        let apiUrl = "https://openrouter.ai/api/v1/chat/completions";
        let headers = {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${GEMINI_API_KEY}`,
            "HTTP-Referer": "https://darkframe.extension",
            "X-Title": "DarkFrame Extension"
        };

        if (endpoint === "groq") {
            apiUrl = "https://api.groq.com/openai/v1/chat/completions";
            const GROQ_API_KEY = process.env.GROQ_API_KEY || GEMINI_API_KEY;
            headers = {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${GROQ_API_KEY}`
            };
        }

        const aiRes = await axios.post(apiUrl, payload, { headers });

        res.json(aiRes.data);
    } catch (error) {
        console.error("AI API error:", error.response ? error.response.data : error.message);
        res.status(500).json({ error: "Failed to get response from AI model." });
    }
});

app.get('/', (req, res) => {
    res.send("DarkFrame Server is running!");
});

// Ping endpoint for UptimeRobot to keep server alive
app.get('/ping', (req, res) => {
    res.status(200).send("pong");
});

app.listen(PORT, () => {
    console.log(`Server listening on port ${PORT}`);
});
